name = "éist"
license = "MIT"
licenselink = "https://github.com/eist-radio/eist/blob/main/LICENSE"
description = "éist is an online radio station based in Cork, Ireland"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.43'

[author]
  name = "Aidan Reilly"
  homepage = "https://github.com/aidanreilly"

[original]
  name = "eist"
  repo = "https://github.com/eist-radio/eist"
